<header class="main-header header">
   <!-- header top -->
   <div class="header-top">
      <div class="container-fluid">
         <nav class="navigation">
            <div class="col-sm-2 col-xs-12">
               <div class="logo"><span>webdesign.net</span></div>
            </div>
            <div class="col-sm-10">
               <ul class="main-menu pull-left">
                  <li>
                     <a href="#"><i class="fa fa-home" aria-hidden="true"></i> Trang chủ</a>
                  </li>
                  <li>
                     <a href="#"><i class="fa fa-user-o" aria-hidden="true"></i> Giới thiệu</a>
                  </li>
                  <li>
                     <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> Liên hệ</a>
                  </li>
                  <li class="category">
                     <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> Khóa học</a>
                  </li>
                  <li class="login">
                     <a href="#">Đăng nhập</a>
                  </li>
                  <li class="register">
                     <a href="#">Đăng ký</a>
                  </li>
               </ul>
               <div class="pull-right">
                     <form name="googleForm" action="" id="form-search">
                        <input name="q" id="q" type="text" class="search-input-box" placeholder="Nhập từ khóa tìm kiếm...">
                        <button type="submit"> <span class="glyphicon glyphicon-search search-icon"></span></button>
                     </form>
               </div>
            </div>
         </nav>
      </div>
   </div>
   <!-- header menu -->
   <div class="header-bottom clearfix">
      <div class="container-fluid">
         <nav id="menu">
            <ul>
               <li class='active'><a href='#'>HOME</a></li>
               <li><a href='#'>ABOUT</a></li>
               <li>
                  <a href='#'><span>Product</span></a>
                  <ul>
                     <li>
                        <a href='#'><span>Product 1</span></a>
                        <ul>
                           <li><a href='#'><span>Product 1</span></a></li>
                           <li><a href='#'><span>Product 2</span></a></li>
                           <li><a href='#'><span>Product 3</span></a></li>
                           <li><a href='#'><span>Product 4</span></a></li>
                        </ul>
                     </li>
                     <li>
                        <a href='#'><span>Product 2</span></a>
                        <ul>
                           <li><a href='#'><span>Product 1</span></a></li>
                           <li><a href='#'><span>Product 2</span></a></li>
                           <li><a href='#'><span>Product 3</span></a></li>
                           <li><a href='#'><span>Product 4</span></a></li>
                        </ul>
                     </li>
                  </ul>
               </li>
               <li><a href='#'>BIO</a></li>
               <li><a href='#'>VIDEO</a></li>
               <li><a href='#'>GALLERY</a></li>
               <li><a href='#'>CONTACT</a></li>
            </ul>
         </nav>
      </div>
   </div>
</header>