<section class="slider" id="particles-js" style="height: 277px;">
	<div id="site-description" class="site-description">
    	<a href="/" title="Trang chủ">
    		<img src="<?php echo $this->url->getBaseUri() ;?>public/templates/assets/images/vDevPro-logo.png" alt="Logo">
    	</a>                                                                
        <p class="z-site-description">Diễn đàn lập trình vDevPro</p>
    </div>
</section>